export const REQUEST_SIGNUP = 'REQUEST_SIGNUP';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const REQUEST_VERIFY_OTP = 'REQUEST_VERIFY_OTP';
export const VERIFY_OTP_SUCCESSFUL = 'VERIFY_OTP_SUCCESSFUL';
export const VERIFY_OTP_ERROR = 'VERIFY_OTP_ERROR';
